apiVersion: secrets.hashicorp.vom/v1beta1 
kind: VaultStaticSecret 
metadata: 
  name: myapp-static-secret 
spec: 
   destination: 
      create: true 
      name: example-of-things 
   hmacSecretData: true
   mount: my-app 
   path: my-app/examples-of-things 
   type: kv-v2 
   vaultAuthRef: myapp-vault-auth

